name: Deploy to AKS

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_NAME }}.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Build and push API image
      run: |
        docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/vocabularyapi:${{ env.IMAGE_TAG }} ./Backend
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/vocabularyapi:${{ env.IMAGE_TAG }}

    - name: Build and push Angular image
      run: |
        docker build -t ${{ secrets.REGISTRY_NAME }}.azurecr.io/vocabularyangular:${{ env.IMAGE_TAG }} ./Frontend
        docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/vocabularyangular:${{ env.IMAGE_TAG }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/vocabularyapi-deployment vocabularyapi=${{ secrets.REGISTRY_NAME }}.azurecr.io/vocabularyapi:${{ env.IMAGE_TAG }}
        kubectl set image deployment/angular-deployment angular=${{ secrets.REGISTRY_NAME }}.azurecr.io/vocabularyangular:${{ env.IMAGE_TAG }}
